# .readthedocs.yml
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  configuration: docs/source/conf.py
  builder: html
  build-dir: docs/build  
  fail_on_warning: true
  build:
    - ./docs/source
  extra:
    # Automatically generate API documentation from module code
    apidoc:
      - module-first
      - -o
      - source/
      - ../src/awsmate

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
